Update dotnet-desktop.yml

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -77,11 +77,42 @@ jobs:
         Configuration: ${{ matrix.configuration }}
 
     # Decode the base 64 encoded pfx and save the Signing_Certificate
+    # Decode the base 64 encoded pfx and save the Signing_Certificate
     - name: Decode the pfx
       run: |
         $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
-        $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath GitHubActionsWorkflow.pfx
+        # Define the certificate path
+        $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath "GitHubActionsWorkflow.pfx"
         [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
+        # Set the path as an output variable
+        Write-Host "certificatePath=$certificatePath" >> $GITHUB_ENV
+
+
+    # Export the certificate to .cer format
+    - name: Export the certificate
+      run: |
+        # Access the certificate path from the environment variable
+        $certificatePath = $env:certificatePath
+        
+        # Check if the certificate file exists
+        if (-Not (Test-Path "$certificatePath")) {
+            Write-Error "The certificate file does not exist at $certificatePath."
+            exit 1
+        }
+    
+        # Create the X509Certificate2 object directly using the .pfx file and password
+        try {
+            $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2("$certificatePath", "${{ secrets.Pfx_Key }}", [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::MachineKeySet)
+        } catch {
+            Write-Error "Failed to load the certificate. Error: $_"
+            exit 1
+        }
+    
+        # Export the certificate to .cer format
+        $cerPath = Join-Path -Path $env:Wap_Project_Directory -ChildPath "ExportedCertificate.cer"
+        [IO.File]::WriteAllBytes("$cerPath", $cert.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert))
+        Write-Host "Certificate exported to $cerPath"
+
 
     # Create the app package by building and packaging the Windows Application Packaging project
     - name: Create the app package
@@ -102,3 +133,10 @@ jobs:
       with:
         name: MSIX_Package-${{ matrix.configuration }}-${{ github.run_id }}
         path: ${{ env.Wap_Project_Directory }}\AppPackages
+
+    # Upload the exported certificate
+    - name: Upload exported certificate
+      uses: actions/upload-artifact@v4
+      with:
+        name: ExportedCertificate
+        path: ${{ env.Wap_Project_Directory }}\ExportedCertificate.cer
